### ISSUE TITLE
Some non-fatal errors

### ISSUE THREAD

**Issue by webmass** [metaphor-xyz/davatar-helpers#20]
Gm,
Thanks for the component

Here's just some minor errors that can show up :
- Inside the useEffect there is need to add a cleanUp function to avoid the "Can't perform a React state update on an unmounted component"
- Some addresses generates this error : **STRINGPREP_CONTAINS_UNASSIGNED**, not sure why but maybe a special character issue, here's an example of address that does that : 0x2e1eEC9908C9E324551B6aABA3e8dC8F255784cb (bull🐋.eth)

Cheers

**Comment by Zimtente** [comment]
> Some addresses generates this error : STRINGPREP_CONTAINS_UNASSIGNED, not sure why but maybe a special character issue, here's an example of address that does that : 0x2e1eEC9908C9E324551B6aABA3e8dC8F255784cb (bull🐋.eth)

any fixes/news?

**Comment by carlosdp** [comment]
I'm not sure that `STRINGPREP_CONTAINS_UNASSIGNED` error is something I can do anything about, I just pass the address string along as I get it. Have you seen this before @ricmoo?

**Comment by ricmoo** [comment]
@carlosdp That error indicates that the name is invalid for STRINGPREP and contains a character forbidden according to the A.1 table in the specification.

ENS is working on expanding the specification of ENS names past STRINGPREP, but that specification hasn’t been formalized yet. It’s coming soon though. And once that has been formalized, ethers will adopt that specification. :)

**Comment by carlosdp** [comment]
Ok gotcha, so it has to do with the ENS name, not the address. Makes sense since it looks like the example one has unicode in it.

Thanks @ricmoo !

That's your answer @webmass @Zimtente , nothing I can do here at the moment. The changes would come on the ethers end once the standardization work that ENS is working on to address names with these kinds of special characters is complete.
